### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by raynor73** [raynor73/AndroidOpenGLResearch2#1]
java.lang.IllegalArgumentException: Vertex shader ambient_vertex_shader already exists
        at ilapin.opengl_research.OpenGLObjectsRepository.createVertexShader(OpenGLObjectsRepository.kt:104)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.setupShaders(GLSurfaceViewRenderer.kt:461)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.onSurfaceChanged(GLSurfaceViewRenderer.kt:89)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

When exiting on Xiaomi MI MAX 2, API 25

**Comment by raynor73** [comment]
Fixed
