### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by raynor73** [raynor73/AndroidOpenGLResearch2#4]
Process: ilapin.opengl_research, PID: 3852
    java.lang.IllegalStateException: Sound player fountain not found
        at ilapin.opengl_research.domain.sound.SoundScene.updateSoundPlayerPosition(SoundScene.kt:176)
        at ilapin.opengl_research.domain.engine.SoundPlayer3DComponent.update(SoundPlayer3DComponent.kt:62)
        at ilapin.engine3d.GameObject.update(GameObject.kt:46)
        at ilapin.engine3d.GameObject.update(GameObject.kt:47)
        at ilapin.engine3d.GameObject.update(GameObject.kt:47)
        at ilapin.opengl_research.domain.ScriptedScene.update(ScriptedScene.kt:105)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.render(GLSurfaceViewRenderer.kt:191)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.onDrawFrame(GLSurfaceViewRenderer.kt:101)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

**Comment by raynor73** [comment]
java.lang.IllegalStateException: Rigid body wood_box not found
        at ilapin.opengl_research.domain.physics_engine.PhysicsEngine.getRigidBodyRotationAndPosition(PhysicsEngine.kt:270)
        at ilapin.opengl_research.domain.engine.RigidBodyGameObjectComponent.update(RigidBodyGameObjectComponent.kt:58)
        at ilapin.engine3d.GameObject.update(GameObject.kt:46)
        at ilapin.engine3d.GameObject.update(GameObject.kt:47)
        at ilapin.opengl_research.domain.ScriptedScene.update(ScriptedScene.kt:104)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.render(GLSurfaceViewRenderer.kt:191)
        at ilapin.opengl_research.ui.GLSurfaceViewRenderer.onDrawFrame(GLSurfaceViewRenderer.kt:101)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
